[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "bcrypt==4.1.1",
    "cryptography==41.0.7",
    "eventlet>=0.41.0",
    "flask==2.3.3",
    "flask-cors==4.0.0",
    "flask-jwt-extended==4.5.2",
    "flask-limiter>=4.1.1",
    "flask-socketio==5.3.5",
    "flask-sqlalchemy==3.1.1",
    "gunicorn==21.2.0",
    "phonenumbers>=9.0.31",
    "pillow==10.1.0",
    "psycopg2-binary==2.9.9",
    "pyjwt==2.8.0",
    "python-dotenv==1.0.0",
    "python-engineio==4.7.1",
    "python-socketio==5.9.0",
    "pywebpush>=2.3.0",
    "qrcode==7.4.2",
    "redis==5.0.1",
    "requests==2.31.0",
    "sqlalchemy==2.0.23",
    "werkzeug==3.0.1",
]
